services:
  - type: web
    name: townhall-icebreaker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: townhall-icebreaker
          property: port